/** 错误码集中定义；api / service / controller 各自包装异常，禁止全局吞掉。 */
export const ERROR_CODES = {
  VALIDATION_FAILED: "VALIDATION_FAILED",
  STORE_UNAVAILABLE: "STORE_UNAVAILABLE",
  NOT_FOUND: "NOT_FOUND",
  DRAFT_NOT_FOUND: "DRAFT_NOT_FOUND",
  DRAFT_ALREADY_FINISHED: "DRAFT_ALREADY_FINISHED",
  QUESTION_INDEX_INVALID: "QUESTION_INDEX_INVALID",
  LESSON_EMPTY: "LESSON_EMPTY",
  LESSON_LOCKED: "LESSON_LOCKED",
  MODE_UNSUPPORTED: "MODE_UNSUPPORTED",
  MASTERY_MARK_CONFLICT: "MASTERY_MARK_CONFLICT",
  EXPORT_FAILED: "EXPORT_FAILED",
  IMPORT_FAILED: "IMPORT_FAILED",
  SEED_FAILED: "SEED_FAILED"
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
