export const ERROR_CODES = {
  AUTH_REQUIRED: "AUTH_REQUIRED",
  RBAC_DENIED: "RBAC_DENIED",
  VALIDATION_FAILED: "VALIDATION_FAILED",
  RATE_LIMITED: "RATE_LIMITED",
  // 练习模式链路相关错误码
  DRAFT_NOT_FOUND: "DRAFT_NOT_FOUND",
  ANSWER_NOT_IN_DRAFT: "ANSWER_NOT_IN_DRAFT",
  SESSION_INCOMPLETE: "SESSION_INCOMPLETE",
  UNSUPPORTED_PRACTICE_MODE: "UNSUPPORTED_PRACTICE_MODE",
  UNSUPPORTED_SYMBOL_CATEGORY: "UNSUPPORTED_SYMBOL_CATEGORY",
  LESSON_EMPTY: "LESSON_EMPTY",
  GRADE_FAILED: "GRADE_FAILED",
  DB_ERROR: "DB_ERROR",
  DEPENDENCY_FAILED: "DEPENDENCY_FAILED"
} as const;

export type ErrorCode = keyof typeof ERROR_CODES;
